INSERT INTO
  users (name, age, position)
VALUES
  ('Alice Johnson', 30, 'Software Engineer'),
  ('Bob Smith', 45, 'Product Manager'),
  ('Charlie Brown', 28, 'UX Designer'),
  ('Diana Prince', 35, 'Marketing Specialist'),
  ('Edward Blake', 50, 'Chief Technology Officer'),
  ('Fiona Glenanne', 40, 'Sales Executive'),
  ('George Washington', 60, 'Consultant'),
  ('Hannah Montana', 22, 'Intern'),
  ('Ivy League', 33, 'Data Scientist'),
  ('Jack Daniels', 29, 'DevOps Engineer'),
  ('Kelly Green', 37, 'HR Manager'),
  ('Liam Neeson', 52, 'Quality Assurance'),
  ('Mia Farrow', 25, 'Graphic Designer'),
  ('Nathan Drake', 31, 'Business Analyst'),
  ('Olivia Pope', 39, 'Legal Advisor'),
  ('Paul Atreides', 47, 'Product Owner'),
  ('Quinn Fabray', 26, 'Project Coordinator'),
  ('Rachel Green', 34, 'Customer Support'),
  ('Sam Winchester', 43, 'Systems Administrator'),
  ('Tina Fey', 38, 'Content Strategist'),
  ('Ursula K. Le Guin', 42, 'Creative Director'),
  ('Vince Vaughn', 41, 'Account Executive'),
  ('Wendy Darling', 27, 'Social Media Manager'),
  ('Xander Harris', 29, 'Network Engineer'),
  ('Yasmine Bleeth', 44, 'Recruiter'),
  ('Zach Morris', 35, 'Operations Manager'),
  ('Anna Kendrick', 24, 'Junior Developer'),
  ('Bill Gates', 60, 'Senior Advisor'),
  ('Catherine Zeta-Jones', 48, 'Strategic Planner'),
  ('Daniel Craig', 50, 'Database Administrator'),
  ('Emma Watson', 32, 'Web Developer'),
  ('Freddie Mercury', 45, 'Sales Manager'),
  ('Gwen Stefani', 38, 'Event Planner'),
  ('Harry Potter', 33, 'IT Support Specialist'),
  ('Isla Fisher', 29, 'PR Specialist'),
  ('James Bond', 55, 'Risk Manager'),
  ('Kylie Minogue', 40, 'Marketing Director'),
  ('Leonardo DiCaprio', 49, 'Finance Manager'),
  ('Meryl Streep', 60, 'Training Coordinator'),
  ('Nina Dobrev', 27, 'Product Designer'),
  ('Orlando Bloom', 37, 'Supply Chain Manager'),
  ('Penelope Cruz', 43, 'Business Development'),
  ('Quincy Jones', 70, 'Music Producer'),
  ('Rihanna', 36, 'Brand Manager'),
  ('Steve Jobs', 65, 'Innovation Lead'),
  ('Terry Crews', 50, 'Customer Success Manager'),
  ('Uma Thurman', 44, 'Executive Assistant'),
  ('Vera Wang', 52, 'Operations Director'),
  ('Will Smith', 45, 'Chief Marketing Officer'),
  ('Xena Warrior', 39, 'Creative Strategist'),
  ('Yoko Ono', 91, 'Cultural Ambassador'),
  ('Zoe Saldana', 36, 'Tech Lead');
