name: Format SQL Files

on:
  pull_request:
    paths:
      - '**/*.sql'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Format SQL files
      uses: docker://node:16 # Use a Docker image with Node.js
      run: |
        npm install -g sql-formatter prettier # Install globally
        sql-formatter --config .sql-formatter.json --write '**/*.sql'
        prettier --write '**/*.sql'

    - name: Check for uncommitted changes
      run: |
        git diff --exit-code || (echo 'SQL files are not formatted. Please format your SQL files before committing.' && exit 1)
