name: Format SQL Files

on:
  pull_request:
    paths:
      - '**/*.sql'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Format SQL files
      uses: my-actions/sql-formatter-action@v1 # Hypothetical action
      with:
        args: '--config .sql-formatter.json --write **/*.sql'

    - name: Check for uncommitted changes
      run: |
        git diff --exit-code || (echo 'SQL files are not formatted. Please format your SQL files before committing.' && exit 1)