name: Format Python Code
on: push
jobs:
    python-code-format:
        runs-on: ubuntu-20.04
        steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-python@v4
           with:
            python-version: "3.10"
            architecture: "x64"
         - name: Display Python version
           run: python --version
         - name: Install packages
           run: pip install black autopep8 isort
         - name: Formatter
           run: |
            black .
            autopep8 --recursive --in-place --aggressive --aggressive .
            isort .
         - name: Commit and push formatted files
           run: |
            git config --global user.name 'github-actions'
            git config --global user.email 'actions@github.com'
            git add '**/*.py'
            git diff --cached --quiet || (
            git commit -m 'Auto-format Py files'
            git push
            )